add sulution for 04-lection2-01-histogram
js-tasks-ru/htmlcss-20210812_morisa pull request #9
Opened 2021-08-29 09:04 UTC by morisa1

2021-08-29 09:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-08-29 09:45 UTC, GSemikozov requested changes

2021-08-29 09:45 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +  width: 9%;
здесь скорее min-width: 9px (как в макете) + flex-grow: 1 на случай если колонок будет меньше но их все равно надо растягивать на всю ширину

2021-08-29 20:20 UTC, morisa1 commented on 04-lection2/01-histogram/histogram.css
> +  width: 9%;
исправила

2021-08-30 08:33 UTC, GSemikozov approved these changes

2021-08-30 08:33 UTC, merged